name: Rolib2

on:
  push:

jobs:
  build:
    name: Run the java unit tests
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build, run tests and build package
        run: |
          mvn package -f pom.xml
      - name: Extract java project version number
        id: version
        run: |
          VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version 2>/dev/null | grep '^[0-9]')
          echo ::set-output name=version::$VERSION
      - name: Upload package artifact for post-deploy job
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: target/rolib-${{ steps.version.outputs.version }}-jar-with-dependencies.jar
      